"""add_connected_battery-status_remaining-battery_fields

Revision ID: 5acc430ba14e
Revises: bf32b90d45c6
Create Date: 2023-09-13 01:23:50.494347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5acc430ba14e"
down_revision: Union[str, None] = "bf32b90d45c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("robots", sa.Column("connected", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "robots", sa.Column("battery_health", sa.SmallInteger(), server_default=sa.text("100"), nullable=False)
    )
    op.add_column(
        "robots", sa.Column("remaining_battery", sa.SmallInteger(), server_default=sa.text("100"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("robots", "remaining_battery")
    op.drop_column("robots", "battery_health")
    op.drop_column("robots", "connected")
    # ### end Alembic commands ###
