"""add_system_status_field

Revision ID: bf32b90d45c6
Revises: 003939bcc656
Create Date: 2023-09-12 01:53:50.246004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.schemas.robot import RobotStatus


# revision identifiers, used by Alembic.
revision: str = "bf32b90d45c6"
down_revision: Union[str, None] = "003939bcc656"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    robotstatus_enum = sa.Enum(RobotStatus, name="robotstatus")
    robotstatus_enum.create(op.get_bind(), checkfirst=False)  # type: ignore

    op.add_column(
        "robots",
        sa.Column(
            "system_status",
            sa.Enum("IDLE", "MOVING", "PAUSED", "CHARGING", "ERROR", name="robotstatus"),
            server_default="IDLE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("robots", "system_status")

    robotstatus_enum = sa.Enum(RobotStatus, name="robotstatus")
    robotstatus_enum.drop(op.get_bind())  # type: ignore
    # ### end Alembic commands ###
